from __future__ import annotations

import re
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


_SECRET_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"password\s*[=:]\s*\S", re.IGNORECASE),
    re.compile(r"secret\s*[=:]\s*\S", re.IGNORECASE),
    re.compile(r"api[_\-]?key\s*[=:]\s*\S", re.IGNORECASE),
    re.compile(r"authorization\s*:\s*bearer\s+\S", re.IGNORECASE),
    re.compile(r"token\s*[=:]\s*\S", re.IGNORECASE),
]


def _contains_secret(value: str) -> bool:
    return any(p.search(value) for p in _SECRET_PATTERNS)


class AuditOutcome(str, Enum):

    SUCCESS = "success"
    FAILED = "failed"
    CANCELLED = "cancelled"
    ROLLED_BACK = "rolled_back"
    PENDING = "pending"


class ConfirmationRecord(BaseModel):

    model_config = ConfigDict(extra="forbid", frozen=True)

    confirmed: bool = Field(description="True = user typed confirmation literal / 'y'.")
    method: str = Field(
        description="How confirmation was requested, e.g. 'yes/no prompt' or "
        "'CONFIRM DELETE typed literal'.",
        max_length=200,
    )
    confirmed_at: datetime | None = Field(
        default=None,
        description="UTC wall-clock time when the user confirmed. None if cancelled.",
    )

    @field_validator("method")
    @classmethod
    def _no_secret_in_method(cls, v: str) -> str:
        if _contains_secret(v):
            raise ValueError(
                "ConfirmationRecord.method appears to contain a secret. "
                "Scrub credentials before logging (CLAUDE.md Section 48)."
            )
        return v


class ExecutionResult(BaseModel):

    model_config = ConfigDict(extra="forbid", frozen=True)

    success: bool
    commands_applied: int = Field(
        ge=0,
        description="Number of RouterOS API calls that were dispatched.",
    )
    summary: str = Field(max_length=500, default="")
    error: str | None = Field(
        default=None,
        max_length=1000,
        description="Error message when success=False. Never a stack trace with secrets.",
    )

    @field_validator("summary", "error")
    @classmethod
    def _no_secret(cls, v: str | None) -> str | None:
        if v and _contains_secret(v):
            raise ValueError(
                "ExecutionResult field appears to contain a secret. "
                "Scrub credentials before logging (CLAUDE.md Section 48)."
            )
        return v


class VerificationResult(BaseModel):

    model_config = ConfigDict(extra="forbid", frozen=True)

    verified: bool
    checks_passed: int = Field(ge=0)
    checks_failed: int = Field(ge=0)
    notes: str | None = Field(
        default=None,
        max_length=1000,
        description="Human-readable summary of what was checked.",
    )

    @model_validator(mode="after")
    def _consistency(self) -> "VerificationResult":
        total = self.checks_passed + self.checks_failed
        if total == 0 and self.verified:
            raise ValueError(
                "verified=True but no checks recorded "
                "(checks_passed=0, checks_failed=0)."
            )
        if self.checks_failed > 0 and self.verified:
            raise ValueError(
                f"verified=True but checks_failed={self.checks_failed}. "
                "Set verified=False when any check fails."
            )
        return self


class RollbackResult(BaseModel):

    model_config = ConfigDict(extra="forbid", frozen=True)

    attempted: bool
    success: bool
    notes: str | None = Field(default=None, max_length=1000)

    @model_validator(mode="after")
    def _attempted_if_succeeded(self) -> "RollbackResult":
        if self.success and not self.attempted:
            raise ValueError(
                "success=True implies attempted=True. "
                "Set attempted=True when the rollback was executed."
            )
        return self


class AuditRecord(BaseModel):

    model_config = ConfigDict(extra="forbid")


    id: str = Field(
        description="Unique record ID (UUID4 as string). Generated by AuditLogger.",
    )

    timestamp: datetime = Field(
        description="UTC wall-clock time when the record was created.",
    )

    user: str = Field(
        min_length=1,
        max_length=200,
        description="OS-level username of the operator.",
    )

    router: str = Field(
        min_length=1,
        max_length=500,
        description="Router identifier (hostname, IP, or user-assigned label). "
        "MUST NOT include credentials.",
    )

    routeros_version: str | None = Field(
        default=None,
        max_length=50,
        description="RouterOS version string reported by the router, e.g. '7.14.3'.",
    )


    request: str = Field(
        min_length=1,
        max_length=2000,
        description="The raw natural-language request typed by the user. "
        "Secrets MUST be redacted before reaching this field.",
    )

    intent: dict[str, Any] | None = Field(
        default=None,
        description="Structured intent as produced by the AI provider (F6). "
        "Pass intent.model_dump(). Never include raw LLM output.",
    )

    plan: dict[str, Any] | None = Field(
        default=None,
        description="Deterministic plan as produced by the Planner (F8). "
        "Pass plan.model_dump().",
    )


    confirmation: ConfirmationRecord | None = Field(
        default=None,
        description="User confirmation record. None for read-only intents.",
    )

    execution_result: ExecutionResult | None = Field(
        default=None,
        description="Execution outcome. None if execution never started.",
    )

    verification_result: VerificationResult | None = Field(
        default=None,
        description="Post-execution verification. None if execution never ran.",
    )

    rollback_result: RollbackResult | None = Field(
        default=None,
        description="Rollback outcome. None if rollback was not attempted.",
    )

    outcome: AuditOutcome = Field(
        default=AuditOutcome.PENDING,
        description="Overall outcome of the action.",
    )


    @field_validator("user", "router", "request")
    @classmethod
    def _no_secret_in_text_fields(cls, v: str) -> str:
        if _contains_secret(v):
            raise ValueError(
                f"AuditRecord text field appears to contain a credential. "
                "Scrub secrets before logging (CLAUDE.md Section 48)."
            )
        return v

    @field_validator("routeros_version")
    @classmethod
    def _version_format(cls, v: str | None) -> str | None:
        if v is not None:
            if not re.match(r"^\d[\d\.a-zA-Z\-]{0,30}$", v):
                raise ValueError(
                    f"routeros_version {v!r} does not look like a RouterOS version "
                    "string (e.g. '7.14.3'). If this is intentional, file an issue."
                )
        return v

    @model_validator(mode="after")
    def _outcome_consistency(self) -> "AuditRecord":
        if self.outcome == AuditOutcome.SUCCESS:
            if self.execution_result is None or not self.execution_result.success:
                raise ValueError(
                    "outcome=SUCCESS requires execution_result with success=True."
                )
        if self.outcome == AuditOutcome.ROLLED_BACK:
            if self.rollback_result is None or not self.rollback_result.attempted:
                raise ValueError(
                    "outcome=ROLLED_BACK requires rollback_result with attempted=True."
                )
        return self
